// src/components/Album.vue
<style lang="stylus">
  .Album {
    display grid
    grid-template-columns 10em auto
    grid-column-gap 1em

    color inherit
    text-decoration none

    background-color rgba(#fff, 0.05)
  }

  .Album-cover {
    width 100%
  }

  .Album-content {
    display flex
    flex-direction column
    justify-content center

    h3 {
      margin-bottom 0rem
    }

    h2 {
      margin-bottom 0.5rem
    }

    p {
      margin-bottom 0.5rem
      text-transform capitalize
    }
  }
</style>

<template>
  <a
    class="Album"
    :href="album.external_urls.spotify"
    target="_blank"
  >
    <img
      class="Album-cover"
      :src="album.cover"
    />

    <div class="Album-content">
      <h3>{{ album.artists }}</h3>
      <h2>{{ album.name }}</h2>
      <p>{{ album.album_type }}</p>
      <p>{{ album.date }}</p>
    </div>
  </a>
</template>

<script>
  export default {
    name: 'Album',

    props: {
      album: {
        type: Object
      }
    },

    methods: {
      concatArtists (artists) {
        return artists.map(artist => artist.name).join(', ')
      },

      getCover (album) {
        const index = Math.min(2, album.images.length) - 1
        return album.images[index].url
      }
    }
  }
</script>

// src/components/Album.svelte
<script>
  export let album
</script>

<div class="Album">
  <a class="Album-wrapper" href={album.external_urls.spotify} target="_blank">
    <img class="Album-cover" src={album.cover} alt="" />

    <div class="Album-content">
      <h3>{album.artists}</h3>
      <h2>{album.name}</h2>
      <p>{album.album_type}</p>
      <p>{album.date}</p>
      <!-- <pre>
        {JSON.stringify(album, null, 2)}
      </pre> -->
    </div>
  </a>

  <img class="Album-backdrop" src={album.cover} alt="" />
</div>

<style>
  .Album {
    position: relative;
    border-radius: 0.5em;
    overflow: hidden;
  }

  .Album-wrapper {
    display: grid;
    grid-template-columns: 10em auto;
    grid-column-gap: 1em;
    padding: 1em;

    color: inherit;
    text-decoration: none;
    background-color: rgba(#fff, 0.05);
    transition-duration: 0.2s;
    transition-property: background-color;
    z-index: 1;
  }

  .Album-cover {
    display: block;
    aspect-ratio: 1 / 1;
    width: 100%;
    border-radius: 3px;
    overflow: hidden;
    box-shadow: 0 2px 4px rgba(#000, 0.2);
    transition-duration: 0.1s;
    transition-property: transform, box-shadow;
  }

  .Album:hover .Album-cover {
    transform: scale(1.05);
    box-shadow: 0 3px 8px rgba(#000, 0.3);
  }

  .Album-backdrop {
    position: absolute;
    inset: -20px;
    width: calc(100% + 40px);
    object-fit: cover;
    filter: blur(20px);
    opacity: 0.2;
    transition-duration: 0.2s;
    transition-property: opacity;
  }

  .Album:hover .Album-backdrop {
    opacity: 0.4;
  }

  .Album-content {
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  .Album-content h3 {
    margin-bottom: 0rem;
  }

  .Album-content h2 {
    margin-bottom: 0.5rem;
  }

  .Album-content p {
    margin-bottom: 0.5rem;
    text-transform: capitalize;
  }
</style>
