// src/components/Footer.vue
<style lang="stylus">
  .Footer {
    padding 1em
    text-align center

    a {
      color inherit
      font-size 0.75em
    }
  }
</style>

<template>
  <footer class="Footer">
    <a href="https://danieldiekmeier.de/impressum.html">Impressum</a>
  </footer>
</template>

<script>
  export default {

  }
</script>

// src/components/Footer.svelte
<footer class="Footer">
  <a href="https://danieldiekmeier.de/impressum.html">Impressum</a>
  &
  <a href="https://danieldiekmeier.de/datenschutz.html">Datenschutzerklärung</a>
</footer>

<style>
  .Footer {
    padding: 1em;
    text-align: center;
    font-size: 0.75em;
  }

  .Footer a {
    color: inherit;
  }
</style>
